# Postgre baasist andmete pärimine

In [1]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.11-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------- ----------------- 1.6/2.8 MB 12.1 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 14.3 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [9]:
import pandas as pd
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="cafe",
    user="postgres",
    password="Parool11"
)

df = pd.read_sql("Select * FROM cafe_sales.cafe_sales_cleaned", conn)
conn.close()
df

C:\Users\opilane\AppData\Local\Temp\ipykernel_6448\666802684.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("Select * FROM cafe_sales.cafe_sales_cleaned", conn)

,transaction_id,item_cleaned,quantity,unit_price,total_spent_calc,payment_method_cleaned,location_cleaned,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9029,TXN_4766549,Smoothie,2,4.0,8.0,Cash,UNKNOWN,2023-10-20
9030,TXN_7851634,UNKNOWN,4,4.0,16.0,UNKNOWN,UNKNOWN,2023-01-08
9031,TXN_7672686,Coffee,2,2.0,4.0,UNKNOWN,UNKNOWN,2023-08-30
9032,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,UNKNOWN,2023-03-02
9033,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [10]:
!pip install requests

Requirement already satisfied: requests in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from requests) (2026.2.25)

## Päringu tegemine veebilehele, näiteks json'i testlehele

In [11]:
import pandas as pd
import requests

In [12]:
response = requests.get("https://jsonplaceholder.typicode.com/posts")
response

In [13]:
response.json()[:3]

[{'userId': 1,
  'id': 1,
  'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'},
 {'userId': 1,
  'id': 2,
  'title': 'qui est esse',
  'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'},
 {'userId': 1,
  'id': 3,
  'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}]

In [14]:
df = pd.DataFrame(response.json())
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

## Vigade haldus

In [ ]:
countries = ["Estonia", "Latvia", "Lithuania"]

try:
    fourth_country

In [9]:
def numeric_year(year_str: str) -> int:
    year_number_components = year_str.split()
    if len(year_number_components) != 2:
        raise ValueError(f"'{year_str}' is not a valid year number: exactly two components expected")
    year_number_str = year_number_components[0]
    year_era_notation_str = year_number_components[1]

    if year_era_notation_str == "A.D.":
        return int(year_number_str)
    elif year_era_notation_str == "B.C.":
        return -int(year_number_str)
    else:
        raise ValueError(f"'{year_str}' does not seem to be a valid year number: unknown era")

print(numeric_year("2024 A.D.")) # 2024
print(numeric_year("1 B.C.")) # -1
print(numeric_year("12 A.D.")) # -1
print(numeric_year("12A.O.")) # 12

2024
-1
12

ValueError: '12A.O.' is not a valid year number: exactly two components expected

In [1]:
"2024 A.D.".split()

['2024', 'A.D.']

In [14]:
def numeric_year(year_str: str) -> int:
    year_number_components = year_str.split()
    if len(year_number_components) != 2:
        raise ValueError(f"'{year_str}' is not a valid year number: exactly two components expected")
    year_number_str = year_number_components[0]
    year_era_notation_str = year_number_components[1]

    try:
        year_numeric = int(year_number_str)
    except:
        raise ValueError(f"'{year_str}' is not a valid year number: year not numeric")
    if year_era_notation_str == "A.D.":
        return year_numeric
    elif year_era_notation_str == "B.C.":
        return -year_numeric
    else:
        raise ValueError(f"'{year_str}' does not seem to be a valid year number: unknown era")

print(numeric_year("2024 A.D.")) # 2024
print(numeric_year("1 B.C.")) # -1
print(numeric_year("12 A.D.")) # -1
print(numeric_year("Kaksteist A.D.")) # 12

2024
-1
12

ValueError: 'Kaksteist A.D.' is not a valid year number: year not numeric

In [ ]:
def numeric_year(year_str: str) -> int:
    """
    Convert a year in format "2025 A.D." or "2025 B.C." to numeric
    """
    # Ensure input has two components corresponding to year and era
    try:
        year_number_str, year_era_notation_str = year_str.split()
    except:
        raise ValueError(f"'{year_str}' is not a valid year number: exactly two components expected")

    # Ensure year number is numeric
    try:
        year_numeric = int(year_number_str)
    except:
        raise ValueError(f"'{year_str}' is not a valid year number: year not numeric")
    
    # Determin sign based on era identifier
    if year_era_notation_str == "A.D.":
        return year_numeric
    if year_era_notation_str == "B.C.":
        return -year_numeric
    raise ValueError(f"'{year_str}' does not seem to be a valid year number: unknown era")

print(numeric_year("2024 A.D.")) # 2024
print(numeric_year("1 B.C.")) # -1
print(numeric_year("12 A.D.")) # -1
# print(numeric_year("Kaksteist A.D.")) # 12

2024
-1
12